### ISSUE TITLE
Import issues on Python 3.12 

### ISSUE THREAD

**Issue by levitsky** [mobiusklein/psims#22]
Importing `psims` fails on Python 3.12 with:

```python
>>> import psims
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lev/.pyenv/versions/py3.12/lib/python3.12/site-packages/psims/__init__.py", line 6, in <module>
    from .mzml import (
  File "/home/lev/.pyenv/versions/py3.12/lib/python3.12/site-packages/psims/mzml/__init__.py", line 1, in <module>
    from .writer import (
  File "/home/lev/.pyenv/versions/py3.12/lib/python3.12/site-packages/psims/mzml/writer.py", line 27, in <module>
    from psims.xml import CVParam, XMLWriterMixin, XMLDocumentWriter
  File "/home/lev/.pyenv/versions/py3.12/lib/python3.12/site-packages/psims/xml.py", line 19, in <module>
    from .validation import validate
  File "/home/lev/.pyenv/versions/py3.12/lib/python3.12/site-packages/psims/validation/__init__.py", line 1, in <module>
    from .validator import validate
  File "/home/lev/.pyenv/versions/py3.12/lib/python3.12/site-packages/psims/validation/validator.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Apparently, this is fixed with `pip install setuptools`.

I noticed this while dealing with a similar problem with `pyteomics`, Curiously, `import pyteomics` does not fail for me locally the same way it does [in a Github runner](https://github.com/levitsky/pyteomics/actions/runs/6739504814/job/18321104453), nor do most of the tests except `proforma` (which fails due to to the error above making it think `psims` is not installed). Hopefully, adding `setuptools` as a requirement should fix all issues, though, otherwise a proper replacement of `pkg_resources` with a more modern API is needed.

**Comment by mobiusklein** [comment]
Thank you for reporting this. The `validator` sub-module isn't even a working feature anymore. I've removed the global import for `pkg_resources` and replaced it with the appropriate `importlib.resources` function, and added unit testing for Py3.11 and 3.12. This seems to be working on Github Actions.

I'll begin a new release process now.

**Comment by mobiusklein** [comment]
v1.3.1 should be live on PyPI where this will have been fixed. Please let me know if there are other issues related to the new Python version.

**Comment by levitsky** [comment]
Thank you! pyteomics tests are now running fine, so no issues left that I know of.
